# Generated by Django 5.0.6 on 2024-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=255, unique=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('logo_of_company', models.ImageField(blank=True, unique=True, upload_to='logos')),
                ('logo_of_company_small', models.ImageField(blank=True, unique=True, upload_to='logos')),
                ('about', models.TextField(blank=True)),
            ],
        ),
    ]
