# Generated by Django 5.0.6 on 2024-07-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(blank=True, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Почтовый ящик'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сфера'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_of_company',
            field=models.ImageField(blank=True, unique=True, upload_to='logos', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_of_company_small',
            field=models.ImageField(blank=True, unique=True, upload_to='logos', verbose_name='Миниатюра лого'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, unique=True, verbose_name='Веб-сайт'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Вакансия')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('speciality', models.CharField(max_length=255, verbose_name='Специальность')),
                ('description', models.TextField(blank=True, verbose_name='Описание вакансии')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Расположение')),
                ('salary', models.IntegerField(blank=True, verbose_name='Зарплата')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('benefits', models.TextField(blank=True, verbose_name='Преимущества')),
                ('skills', models.JSONField(blank=True, verbose_name='Необходимые навыки')),
                ('type_of_employment', models.CharField(blank=True, max_length=255, verbose_name='Вид трудоустройства')),
                ('url_for_vacancy', models.URLField(blank=True, max_length=255, unique=True, verbose_name='Ссылка на вакансию')),
                ('contact_email', models.EmailField(max_length=255, unique=True, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(max_length=255, unique=True, verbose_name='Контактный телефон')),
                ('logo_of_vacancy', models.ImageField(blank=True, unique=True, upload_to='logos', verbose_name='Лого')),
                ('logo_of_vacancy_small', models.ImageField(blank=True, unique=True, upload_to='logos', verbose_name='Миниатюра лого')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
