# Generated by Django 5.0.6 on 2024-07-31 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_company_options_alter_company_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseToVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Отклик'), ('Interview', 'Собеседование'), ('Rejected', 'Отказ'), ('Offered', 'Офер')], default='Applied', max_length=15, verbose_name='Статус отклика')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('send_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отклика')),
                ('response_date', models.DateTimeField(auto_now=True, verbose_name='Дата ответа на отклик')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.vacancy', verbose_name='Вакансия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.user', verbose_name='Пользователь')),
            ],
        ),
    ]
