# Generated by Django 5.0.6 on 2024-07-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_responsetovacancy_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(db_index=True, default=88005553535, max_length=20, unique=True, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Почтовый ящик'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contact_email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Контактный email'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contact_phone',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.JSONField(blank=True, verbose_name='Требуемые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type_of_employment',
            field=models.CharField(choices=[('Full_time', 'Полная занятость'), ('Part_time', 'Частичная занятость'), ('Contract', 'Контракт'), ('Internship', 'Стажировка'), ('Shift_work', 'Вахтовый метод')], default='Full_time', max_length=20, verbose_name='Вид трудоустройства'),
        ),
    ]
