# Generated by Django 5.0.6 on 2024-07-31 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_company_phone_alter_company_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='JobApplicant',
        ),
        migrations.AlterModelOptions(
            name='jobapplicant',
            options={'verbose_name': 'Соискатель', 'verbose_name_plural': 'Соискатели'},
        ),
        migrations.RemoveField(
            model_name='responsetovacancy',
            name='user',
        ),
        migrations.AddField(
            model_name='responsetovacancy',
            name='job_applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='staff.jobapplicant', verbose_name='Соискатель'),
            preserve_default=False,
        ),
    ]
