# Generated by Django 5.0.6 on 2024-08-02 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_user_jobapplicant_alter_jobapplicant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Расположение')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
            ],
            options={
                'verbose_name': 'Информация о соискателях',
                'verbose_name_plural': 'Информация о соискателях',
            },
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='date_join',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='desired_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Желаемая локация'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='desired_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Желаемая позиция'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='desired_salary',
            field=models.IntegerField(blank=True, default=31231, verbose_name='Желаемая ЗП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='github_profile',
            field=models.URLField(blank=True, max_length=255, unique=True, verbose_name='GitHub аккаунт'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='password',
            field=models.CharField(default=12312412, max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='resume_url',
            field=models.URLField(blank=True, max_length=255, unique=True, verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='skills',
            field=models.JSONField(blank=True, default={}, verbose_name='Навыки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='username',
            field=models.CharField(db_index=True, default=1, max_length=255, unique=True, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='applicant_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.applicantinfo', verbose_name='Соискатель'),
        ),
    ]
