# Generated by Django 5.0.6 on 2024-08-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_applicantinfo_jobapplicant_date_join_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantinfo',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='applicantinfo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, verbose_name='WhatsApp'),
        ),
    ]
