# Generated by Django 5.0.6 on 2024-08-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_applicantinfo_telegram_applicantinfo_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantinfo',
            options={'verbose_name': 'Информация о соискателе', 'verbose_name_plural': 'Информация о соискателях'},
        ),
    ]
