# Generated by Django 5.0.6 on 2024-08-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_applicantinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='applicant_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.applicantinfo', verbose_name='Соискатель'),
        ),
    ]
