# Generated by Django 5.0.6 on 2024-08-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_jobapplicant_applicant_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название вакансии')),
                ('vacancy_views', models.IntegerField(default=0, verbose_name='Количество просмотров вакансии')),
                ('number_of_resp', models.IntegerField(default=0, verbose_name='Количество откликов')),
                ('number_of_invited', models.IntegerField(default=0, verbose_name='Приглашенных на тех-интервью')),
            ],
            options={
                'verbose_name': 'Статистика вакансии',
                'verbose_name_plural': 'Статистика вакансий',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_statistic',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.vacancystatistic', verbose_name='Статистика вакансии'),
            preserve_default=False,
        ),
    ]
