# Generated by Django 5.0.6 on 2024-08-04 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_vacancystatistic_vacancy_vacancy_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Ключевое слово')),
                ('type', models.CharField(choices=[('Skill', 'Навык'), ('Technology', 'Технология'), ('Position', 'Должность'), ('Industry', 'Индустрия'), ('Privilege', 'Привилегия')], default='Skill', max_length=11, verbose_name='Тип ключевого слова')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.AlterField(
            model_name='responsetovacancy',
            name='job_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='staff.jobapplicant', verbose_name='Соискатель'),
        ),
        migrations.AlterField(
            model_name='responsetovacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='staff.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='staff.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='staff.keyword', verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='staff.keyword', verbose_name='Ключевые слова'),
        ),
    ]
