# Generated by Django 5.0.6 on 2024-08-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_keyword_alter_responsetovacancy_job_applicant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicant',
            name='is_admin',
        ),
    ]
