# Generated by Django 5.0.6 on 2024-08-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_remove_jobapplicant_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_statistic',
        ),
        migrations.AddField(
            model_name='vacancystatistic',
            name='vacancy',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='staff.vacancy', verbose_name='Вакансия'),
            preserve_default=False,
        ),
    ]
